--<ScriptOptions statementTerminator=";"/>

ALTER TABLE "MY_SCHEMA"."JOIN_DELEGATE_EVENT" DROP CONSTRAINT "FK45EF12F5C518F24D";

ALTER TABLE "MY_SCHEMA"."JOIN_DELEGATE_EVENT" DROP CONSTRAINT "FK45EF12F5A9F4C3A7";

DROP INDEX "MY_SCHEMA"."SQL171029221655970";

DROP INDEX "MY_SCHEMA"."SQL171029221655850";

DROP TABLE "MY_SCHEMA"."JOIN_DELEGATE_EVENT";

CREATE TABLE "MY_SCHEMA"."JOIN_DELEGATE_EVENT" (
		"DELEGATEID" INTEGER NOT NULL,
		"EVENTID" INTEGER NOT NULL
	);

CREATE INDEX "MY_SCHEMA"."SQL171029221655970" ON "MY_SCHEMA"."JOIN_DELEGATE_EVENT" ("DELEGATEID" ASC);

CREATE INDEX "MY_SCHEMA"."SQL171029221655850" ON "MY_SCHEMA"."JOIN_DELEGATE_EVENT" ("EVENTID" ASC);

ALTER TABLE "MY_SCHEMA"."JOIN_DELEGATE_EVENT" ADD CONSTRAINT "FK45EF12F5C518F24D" FOREIGN KEY ("EVENTID")
	REFERENCES "MY_SCHEMA"."EVENT" ("EVENTID");

ALTER TABLE "MY_SCHEMA"."JOIN_DELEGATE_EVENT" ADD CONSTRAINT "FK45EF12F5A9F4C3A7" FOREIGN KEY ("DELEGATEID")
	REFERENCES "MY_SCHEMA"."DELEGATE" ("DELEGATEID");

