-- Run Derby in NetworkServer Mode
-- Connect to "dbauth" database
-- Select each SQL statement line and execute (Alt+X in Eclipse on Windows)

TRUNCATE TABLE USERS;
TRUNCATE TABLE ROLES;

DROP TABLE USERS;
DROP TABLE ROLES;

CREATE TABLE USERS (
  USER_ID INT NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
  USERNAME VARCHAR(100) NOT NULL,
  PASSWORD VARCHAR(100) NOT NULL,
  ENABLED INT NOT NULL,
  PRIMARY KEY (USER_ID)
);

CREATE TABLE ROLES (
  USER_ROLE_ID INT NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
  USER_ID INT NOT NULL,
  ROLE VARCHAR(100) NOT NULL,
  PRIMARY KEY (USER_ROLE_ID)
);

SELECT * FROM USERS;
SELECT * FROM ROLES;

INSERT INTO USERS(USERNAME, PASSWORD, ENABLED) VALUES('victor', '123', 1);
INSERT INTO USERS(USERNAME, PASSWORD, ENABLED) VALUES('alan', '123', 1);

INSERT INTO ROLES(USER_ID, ROLE) VALUES((SELECT USER_ID FROM USERS WHERE USERNAME='victor'), 'ADMIN_ROLE');
INSERT INTO ROLES(USER_ID, ROLE) VALUES((SELECT USER_ID FROM USERS WHERE USERNAME='victor'), 'USER_ROLE');
INSERT INTO ROLES(USER_ID, ROLE) VALUES((SELECT USER_ID FROM USERS WHERE USERNAME='alan'), 'USER_ROLE');
